#!/bin/sh

########################################################################
#                                                                      #
# This file is part of Saria’s random message loader program.          #
#                                                                      #
# Saria’s random message loader program is free software: you can      #
# redistribute it and/or modify it under the terms of the GNU          #
# General Public License as published by the Free Software Foundation, #
# either version 3 of the License, or (at your option) any later       #
# version.                                                             #
#                                                                      #
# Saria’s random message loader program is distributed in the hope     #
# that it will be useful, but WITHOUT ANY WARRANTY; without even the   #
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR      #
# PURPOSE. See the GNU General Public License for more details.        #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Saria’s random message loader program.                    #
# If not, see <https://www.gnu.org/licenses/>.                         #
#                                                                      #
########################################################################

set -e
set -u

npm_dir='.npm'

# Find Jest config file, so tests can be run either from project root,
# or from tests directory.
jest_config_filename='jest.config.json'
if [ -f "test/config/${jest_config_filename}" ] ; then
	jest_config_path="test/config/${jest_config_filename}"
elif [ -f "config/${jest_config_filename}" ] ; then
	jest_config_path="config/${jest_config_filename}"
else
	printf '%s: %s\n' "$(basename -- "${0}")" 'could not find Jest configuration' >&2
	exit 1
fi

"${npm_dir}"/bin/jest --config "${jest_config_path}" "${@}"
