########################################################################
#                                                                      #
# This file is part of Saria’s random message loader program.          #
#                                                                      #
# Saria’s random message loader program is free software: you can      #
# redistribute it and/or modify it under the terms of the GNU          #
# General Public License as published by the Free Software Foundation, #
# either version 3 of the License, or (at your option) any later       #
# version.                                                             #
#                                                                      #
# Saria’s random message loader program is distributed in the hope     #
# that it will be useful, but WITHOUT ANY WARRANTY; without even the   #
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR      #
# PURPOSE. See the GNU General Public License for more details.        #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Saria’s random message loader program.                    #
# If not, see <https://www.gnu.org/licenses/>.                         #
#                                                                      #
########################################################################

name: Run tests
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Get npm cache directory
            id: npm-cache-dir
            shell: bash
            run: printf 'dir=%s\n' "$(npm config get cache)" >>${GITHUB_OUTPUT}
          - name: Load npm cache
            uses: actions/cache@v3
            id: npm-cache
            with:
                path: ${{ steps.npm-cache-dir.outputs.dir }}
                key: ${{ runner.os }}-node
                restore-keys: |
                    ${{ runner.os }}-node
          - name: Install test dependencies
            run: test/setup
          - name: Run tests
            run: test/run
